// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: buses.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusNumber int64 `protobuf:"varint,1,opt,name=BusNumber,proto3" json:"BusNumber,omitempty"`
}

func (x *BusRequest) Reset() {
	*x = BusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusRequest) ProtoMessage() {}

func (x *BusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusRequest.ProtoReflect.Descriptor instead.
func (*BusRequest) Descriptor() ([]byte, []int) {
	return file_buses_proto_rawDescGZIP(), []int{0}
}

func (x *BusRequest) GetBusNumber() int64 {
	if x != nil {
		return x.BusNumber
	}
	return 0
}

type BusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float64 `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
}

func (x *BusResponse) Reset() {
	*x = BusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusResponse) ProtoMessage() {}

func (x *BusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusResponse.ProtoReflect.Descriptor instead.
func (*BusResponse) Descriptor() ([]byte, []int) {
	return file_buses_proto_rawDescGZIP(), []int{1}
}

func (x *BusResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *BusResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

var File_buses_proto protoreflect.FileDescriptor

var file_buses_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x75, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x75, 0x73, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0a, 0x42, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x42, 0x75, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x47, 0x0a, 0x0b, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0x43, 0x0a, 0x0a, 0x42, 0x75, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x42, 0x75, 0x73, 0x12, 0x11, 0x2e, 0x62, 0x75, 0x73, 0x65, 0x73, 0x2e, 0x42, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x75, 0x73, 0x65, 0x73,
	0x2e, 0x42, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x75, 0x73, 0x65, 0x73, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buses_proto_rawDescOnce sync.Once
	file_buses_proto_rawDescData = file_buses_proto_rawDesc
)

func file_buses_proto_rawDescGZIP() []byte {
	file_buses_proto_rawDescOnce.Do(func() {
		file_buses_proto_rawDescData = protoimpl.X.CompressGZIP(file_buses_proto_rawDescData)
	})
	return file_buses_proto_rawDescData
}

var file_buses_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_buses_proto_goTypes = []interface{}{
	(*BusRequest)(nil),  // 0: buses.BusRequest
	(*BusResponse)(nil), // 1: buses.BusResponse
}
var file_buses_proto_depIdxs = []int32{
	0, // 0: buses.BusService.RequestBus:input_type -> buses.BusRequest
	1, // 1: buses.BusService.RequestBus:output_type -> buses.BusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_buses_proto_init() }
func file_buses_proto_init() {
	if File_buses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buses_proto_goTypes,
		DependencyIndexes: file_buses_proto_depIdxs,
		MessageInfos:      file_buses_proto_msgTypes,
	}.Build()
	File_buses_proto = out.File
	file_buses_proto_rawDesc = nil
	file_buses_proto_goTypes = nil
	file_buses_proto_depIdxs = nil
}
