# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import metrics_pb2 as metrics__pb2


class MetricsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTemp = channel.unary_unary(
                '/metrics.MetricsService/RequestTemp',
                request_serializer=metrics__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=metrics__pb2.TemperatureResponse.FromString,
                )
        self.RequestPol = channel.unary_unary(
                '/metrics.MetricsService/RequestPol',
                request_serializer=metrics__pb2.PollutionRequest.SerializeToString,
                response_deserializer=metrics__pb2.PollutionResponse.FromString,
                )


class MetricsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestTemp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTemp': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTemp,
                    request_deserializer=metrics__pb2.TemperatureRequest.FromString,
                    response_serializer=metrics__pb2.TemperatureResponse.SerializeToString,
            ),
            'RequestPol': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPol,
                    request_deserializer=metrics__pb2.PollutionRequest.FromString,
                    response_serializer=metrics__pb2.PollutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metrics.MetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetricsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestTemp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics.MetricsService/RequestTemp',
            metrics__pb2.TemperatureRequest.SerializeToString,
            metrics__pb2.TemperatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestPol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics.MetricsService/RequestPol',
            metrics__pb2.PollutionRequest.SerializeToString,
            metrics__pb2.PollutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
