# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x07metrics\"\\\n\x13TemperatureResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\x03\x12\x10\n\x08\x64istrict\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x03\x12\x10\n\x08humidity\x18\x04 \x01(\x03\"N\n\x11PollutionResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\x03\x12\x10\n\x08\x64istrict\x18\x02 \x01(\t\x12\x0b\n\x03\x63o2\x18\x03 \x01(\x03\x12\x0c\n\x04pm25\x18\x04 \x01(\x03\"0\n\x12TemperatureRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t\".\n\x10PollutionRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\t2\xa3\x01\n\x0eMetricsService\x12J\n\x0bRequestTemp\x12\x1b.metrics.TemperatureRequest\x1a\x1c.metrics.TemperatureResponse\"\x00\x12\x45\n\nRequestPol\x12\x19.metrics.PollutionRequest\x1a\x1a.metrics.PollutionResponse\"\x00\x42\x14Z\x12./proto/metrics/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022./proto/metrics/pb'
  _TEMPERATURERESPONSE._serialized_start=26
  _TEMPERATURERESPONSE._serialized_end=118
  _POLLUTIONRESPONSE._serialized_start=120
  _POLLUTIONRESPONSE._serialized_end=198
  _TEMPERATUREREQUEST._serialized_start=200
  _TEMPERATUREREQUEST._serialized_end=248
  _POLLUTIONREQUEST._serialized_start=250
  _POLLUTIONREQUEST._serialized_end=296
  _METRICSSERVICE._serialized_start=299
  _METRICSSERVICE._serialized_end=462
# @@protoc_insertion_point(module_scope)
